[user]
name = "Rintaro Okamura"
email = "rintaro.okamura@gmail.com"

[colors]
wip = "yellow"
todo = "blue"
mega = "red"

[ui]
default-command = ["log"]
editor = "nvim"
diff-editor = "gitpatch"
paginate = "never"
show-cryptographic-signatures = true

# Ref: https://zerowidth.com/2025/jj-tips-and-tricks/#hunk-wise-style
[merge-tools.gitpatch]
program = "sh"
edit-args = [
  "-c",
  '''
  set -eu
  rm -f "$right/JJ-INSTRUCTIONS"
  git -C "$left" init -q
  git -C "$left" add -A
  git -C "$left" commit -q -m baseline --allow-empty
  mv "$left/.git" "$right"
  git -C "$right" add --intent-to-add --ignore-removal .
  git -C "$right" add -p
  git -C "$right" diff-index --quiet --cached HEAD && { echo "No changes done, aborting split."; exit 1; }
  git -C "$right" commit -q -m split
  git -C "$right" reset -q --hard
''',
]

[signing]
behavior = "own"
backend = "gpg"

[aliases]
pre-commit = ["util", "exec", "--", "pre-commit", "run", "--all-files"]

[templates]
commit_trailers = '''
format_signed_off_by_trailer(self)
'''
git_push_bookmark = '''
separate('-', reference_issue('Refs'), slugify(description), change_id.shortest(8))
'''

[template-aliases]

# for zsh prompt
# Ref: https://zerowidth.com/2025/async-zsh-jujutsu-prompt-with-p10k/
prompt = '''
separate(" ",
  format_short_change_id_with_change_offset(self),
  commit_id.shortest(8),
  if(empty, label("empty", "(empty)"), ""),
  if(description == "", label("description placeholder", "(no description)"), ""),
  if(description.starts_with("wip"), label("wip", "(wip)"), ""),
  if(description.starts_with("todo"), label("todo", "(todo)"), ""),
  if(description.starts_with("mega"), label("mega", "(mega)"), ""),
  if(conflict, label("conflict", "(conflict)"), "")
)
'''

# for git_push_bookmark
# Ref: https://ddbeck.com/notes/jj-git-push-bookmark-template/
# Ref: https://lobste.rs/s/r4xf2n/better_generated_branch_names_with_jj
'reference_issue(key)' = '''
  truncate_end(
    16,
    stringify(
      if(trailers.any(|t| t.key() == key && t.value().match(regex:'^[^/]+/[a-zA-Z0-9._-]{1,100}#[0-9]+$')),
          trailers.filter(|t| t.key() == key && t.value().match(regex:'^[^/]+/[a-zA-Z0-9._-]{1,100}#[0-9]+$'))
          .first().value()
          .replace(regex:'^[^/]+/', '')
          .replace(regex:'[^[[:alnum:]].]', '-')
          .replace(regex:'-{2,}', '-')
          .replace(regex:'\.{2,}', '.')
          .replace(regex:'(^-+|-+$)', '')
          .lower(),
          '')))
'''
'slugify(str)' = '''
  truncate_end(
    40,
    str.first_line()
      .replace(regex:'^[^:]+:', '')
      .replace(regex:'[^[[:alnum:]].]', '-')
      .replace(regex:'-{2,}', '-')
      .replace(regex:'\.{2,}', '.')
      .replace(regex:'(^-+|-+$)', '')
      .lower())
'''

# Ref: https://isaaccorbrey.com/notes/jujutsu-megamerges-for-fun-and-profit
[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"
"closest_merge(to)" = "heads(::to & merges())"

# Ref: https://github.com/jj-vcs/jj/discussions/4690#discussioncomment-16870293
# allow for `jj diff` and `jj show` to clear output from terminal after pager closed
[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
# stop using delta as the pager for already-delta-formatted output
pager = ["less", "-FR"] # seems to be default (?)
# keep delta as external diff formatter to diffs real temp files/dir and keep syntax highlighting
diff-formatter = "delta"

# pass jj's computed terminal width via $width
[merge-tools.delta]
diff-args = ["--width=$width", "$left", "$right"]
diff-expected-exit-codes = [0, 1]
