-- [nfnl] Compiled from fnl/rc/colorscheme.fnl by https://github.com/Olical/nfnl, do not edit.
local _local_1_ = require("nfnl.module")
local autoload = _local_1_["autoload"]
local nightfox = require("nightfox")
local color = autoload("rc.color")
local colors = color.colors
nightfox.setup({options = {compile_path = vim.fn.expand("~/.config/nvim/tmp/cache/nightfox"), compile_file_suffix = "_compiled", transparent = true, terminal_colors = true, styles = {comments = "italic", keywords = "bold,italic", functions = "bold", types = "italic"}, dim_inactive = false}})
vim.cmd("silent colorscheme duskfox")
vim.cmd("syntax enable")
vim.cmd(("highlight " .. ((("DiagnosticUnderlineError" .. " " .. ("cterm" .. "=" .. "undercurl")) .. " " .. ("gui" .. "=" .. "undercurl")) .. " " .. ("guisp" .. "=" .. colors.error))))
vim.cmd(("highlight " .. ((("DiagnosticUnderlineWarn" .. " " .. ("cterm" .. "=" .. "undercurl")) .. " " .. ("gui" .. "=" .. "undercurl")) .. " " .. ("guisp" .. "=" .. colors.warn))))
vim.cmd(("highlight " .. ((("DiagnosticUnderlineInfo" .. " " .. ("cterm" .. "=" .. "undercurl")) .. " " .. ("gui" .. "=" .. "undercurl")) .. " " .. ("guisp" .. "=" .. colors.info))))
vim.cmd(("highlight " .. ((("DiagnosticUnderlineHint" .. " " .. ("cterm" .. "=" .. "undercurl")) .. " " .. ("gui" .. "=" .. "undercurl")) .. " " .. ("guisp" .. "=" .. colors.hint))))
vim.cmd(("highlight " .. (("DiagnosticSignError" .. " " .. ("ctermfg" .. "=" .. "red")) .. " " .. ("guifg" .. "=" .. colors.error))))
vim.cmd(("highlight " .. (("DiagnosticSignWarn" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("guifg" .. "=" .. colors.warn))))
vim.cmd(("highlight " .. (("DiagnosticSignInfo" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("guifg" .. "=" .. colors.info))))
vim.cmd(("highlight " .. (("DiagnosticSignHint" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.hint))))
vim.cmd(("highlight " .. (("DiagnosticSignLightBulb" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("guifg" .. "=" .. colors.warn))))
vim.cmd(("highlight " .. (((("DiagnosticVirtualTextError" .. " " .. ("ctermfg" .. "=" .. "red")) .. " " .. ("gui" .. "=" .. "italic")) .. " " .. ("guifg" .. "=" .. colors.error)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. (((("DiagnosticVirtualTextWarn" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("gui" .. "=" .. "italic")) .. " " .. ("guifg" .. "=" .. colors.warn)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. (((("DiagnosticVirtualTextInfo" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("gui" .. "=" .. "italic")) .. " " .. ("guifg" .. "=" .. colors.info)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. (((("DiagnosticVirtualTextHint" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("gui" .. "=" .. "italic")) .. " " .. ("guifg" .. "=" .. colors.hint)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticError" .. " " .. ("ctermfg" .. "=" .. "red")) .. " " .. ("guifg" .. "=" .. colors.color8)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticFloatingError" .. " " .. ("ctermfg" .. "=" .. "red")) .. " " .. ("guifg" .. "=" .. colors.color8)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticWarn" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("guifg" .. "=" .. colors.warn)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticFloatingWarn" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("guifg" .. "=" .. colors.warn)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticHint" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.color10)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticFloatingHint" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.color10)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticInfo" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("guifg" .. "=" .. colors.color13)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("DiagnosticFloatingInfo" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("guifg" .. "=" .. colors.color13)) .. " " .. ("guibg" .. "=" .. colors.color5))))
vim.cmd(("highlight " .. ((("LspCodeLens" .. " " .. ("gui" .. "=" .. "bold,italic,underline")) .. " " .. ("guifg" .. "=" .. colors.color2)) .. " " .. ("guibg" .. "=" .. colors.color10))))
vim.cmd(("highlight " .. (((("TelescopeBorder" .. " " .. ("ctermbg=" .. "none" .. " guibg=" .. "none")) .. " " .. ("blend" .. "=" .. "0")) .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.color10))))
vim.cmd(("highlight " .. (("TelescopePromptPrefix" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.color10))))
vim.cmd(("highlight " .. (("NotifyERROR" .. " " .. ("ctermfg" .. "=" .. "red")) .. " " .. ("guifg" .. "=" .. colors.error))))
vim.cmd(("highlight " .. (("NotifyWARN" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("guifg" .. "=" .. colors.warn))))
vim.cmd(("highlight " .. (("NotifyINFO" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("guifg" .. "=" .. colors.info))))
vim.cmd(("highlight " .. (("NotifyDEBUG" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.hint))))
vim.cmd(("highlight " .. (("NotifyTRACE" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.hint))))
vim.cmd(("highlight " .. (("NotifyERRORTitle" .. " " .. ("ctermfg" .. "=" .. "red")) .. " " .. ("guifg" .. "=" .. colors.error))))
vim.cmd(("highlight " .. (("NotifyWARNTitle" .. " " .. ("ctermfg" .. "=" .. "yellow")) .. " " .. ("guifg" .. "=" .. colors.warn))))
vim.cmd(("highlight " .. (("NotifyINFOTitle" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("guifg" .. "=" .. colors.info))))
vim.cmd(("highlight " .. (("NotifyDEBUGTitle" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.hint))))
vim.cmd(("highlight " .. (("NotifyTRACETitle" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.hint))))
vim.cmd(("highlight " .. (("FidgetTitle" .. " " .. ("ctermfg" .. "=" .. "green")) .. " " .. ("guifg" .. "=" .. colors.info))))
return vim.cmd(("highlight " .. (("FidgetTask" .. " " .. ("ctermfg" .. "=" .. "blue")) .. " " .. ("guifg" .. "=" .. colors.hint))))
