name: benchmark
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Free disk space
        uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        with:
          hatchet-protocol: 'rampage'
          root-safe-haven: '3072' # Reserve 3GB on the / filesystem
          mnt-safe-haven: '2048' # Reserve 2GB on the /mnt filesystem
          nix-permission-edict: true
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
          install_options: --no-daemon
      - name: Setup Cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: rinx
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          skipPush: true
      - name: Install dependencies
        run: |
          nix profile install .
      - name: nvim version
        run: |
          nvim --version
      - name: babashka version
        run: |
          bb --version
      - name: Setup dotfiles
        run: |
          make DOTDIR="$(pwd)" deploy
      - name: Install zsh plugins
        run: |
          zsh -i -c exit
      - name: Install neovim plugins
        run: |
          # Install essential plugins
          nvim --headless -c 'qall'
          # Install other plugins
          nvim --headless -c 'Lazy! sync' -c 'qall'
          # Treesitter
          nvim --headless -c 'TSInstallEnsure' -c 'qall'
          # workaround: Ensure installed correctly
          nvim --headless -c 'TSInstallEnsure' -c 'qall'
          nvim --headless -c 'TSInstallEnsure' -c 'qall'
      - name: Confirm all neovim plugins installed
        run: |
          time nvim --headless -V -c 'qall'
      - name: Run benchmark
        run: |
          bb ./.github/scripts/benchmark.clj | tee benchmark-result.json
      - name: Upload benchmark result
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: benchmark-result.json
          archive: false
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'push'
    needs:
      - benchmark
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Download benchmark result
        id: download_result
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: benchmark-result.json
      - name: Upload benchmark
        uses: benchmark-action/github-action-benchmark@a60cea5bc7b49e15c1f58f411161f99e0df48372 # v1.22.0
        with:
          tool: customSmallerIsBetter
          output-file-path: benchmark-result.json
          gh-pages-branch: gh-pages
          github-token: ${{ steps.generate_token.outputs.token }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: false
          alert-threshold: '150%'
          alert-comment-cc-users: '@rinx'
