name: Build NixOS Lima image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
      fail-fast: false
    env:
      ARCH: ${{ matrix.os == 'ubuntu-24.04' && 'x86_64' || (matrix.os == 'ubuntu-24.04-arm' && 'aarch64') || 'unknown' }}
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
          install_options: --no-daemon
          extra_nix_config: |
            system-features = ${{ env.ARCH == 'aarch64' && 'kvm aarch64-linux' || 'kvm' }}
      - name: Setup Cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: rinx
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          skipPush: true
      - name: Build ${{ env.ARCH }} image
        run: |
          nix build .#packages.${{ env.ARCH }}-linux.lima-img --out-link result-${{ env.ARCH }}
          qemu-img convert -O qcow2 -c result-${{ env.ARCH }}/nixos.qcow2 nixos-lima-${{ env.ARCH }}.qcow2
      - name: Upload image
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: nixos-lima-${{ env.ARCH }}.qcow2
          archive: false
