name: Update dependencies
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 17 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Install babashka
        run: |
          bash <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install) --dir $(pwd)
          ./bb --version
      - name: Update deps
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          ./bb ./.github/scripts/deps-update.clj
          rm -f ./bb
      - name: Check and Push to main
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          if git diff --quiet --exit-code; then
            echo "Nothing updated"
          else
            git config --global user.email "$(gh api -q .id "users/${NAME}")+rinx-app[bot]@users.noreply.github.com"
            git config --global user.name "rinx-app[bot]"

            git add Dockerfile Makefile.d/bin.mk

            git commit --signoff -m "[patch] :robot: Automatically upgrade dependencies."

            git push origin main
          fi
