name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  sg-scan:
    name: Scan using ast-grep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup Cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: rinx
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          skipPush: true
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: Run ast-grep with reviewdog
        uses: reviewdog/action-ast-grep@e842b1943f645379f3063d1748044ec008b647b6 # v1.53.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          filter_mode: nofilter
          reviewdog_flags: -tee
  test-sg-rules:
    name: Test ast-grep rules
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Setup Cachix
        uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: rinx
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
          skipPush: true
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: Run ast-grep rule tests
        run: |
          ast-grep test
