name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  sg-scan:
    name: Scan using ast-grep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: Run ast-grep with reviewdog
        uses: reviewdog/action-ast-grep@14690d058ff47b2fa9f155d69dbd3e1fb5695bbe # v1.53.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: info
          reporter: ${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}
          filter_mode: nofilter
          reviewdog_flags: -tee
  test-sg-rules:
    name: Test ast-grep rules
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/install-nix-action@96951a368ba55167b55f1c916f7d416bac6505fe # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: Run ast-grep rule tests
        run: |
          ast-grep test
