name: Report nix diff
on:
  pull_request:
    paths:
      - flake.lock
jobs:
  dix:
    name: nix diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Free disk space
        uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        with:
          hatchet-protocol: 'rampage'
          root-safe-haven: '3072' # Reserve 3GB on the / filesystem
          mnt-safe-haven: '2048' # Reserve 2GB on the /mnt filesystem
          nix-permission-edict: true
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
          install_options: --no-daemon
      - uses: natsukium/nix-diff-action@b5c316c6cafc8470037d7f330b178aaeeba96ba4 # v1.1.0
        with:
          attributes: |
            - displayName: packages
              attribute: default
