name: Report nix diff
on:
  pull_request:
    paths:
      - flake.lock
jobs:
  dix:
    name: nix diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Free disk space
        uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        with:
          hatchet-protocol: 'rampage'
          root-safe-haven: '3072' # Reserve 3GB on the / filesystem
          mnt-safe-haven: '2048' # Reserve 2GB on the /mnt filesystem
          nix-permission-edict: true
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31
        with:
          github_access_token: ${{ steps.generate_token.outputs.token }}
          nix_path: nixpkgs=channel:nixos-unstable
          install_options: --no-daemon
      - uses: natsukium/nix-diff-action@65526931655c9561dfdb1330b8770d1673857ae9 # v1.0.3
        with:
          attributes: |
            - displayName: packages
              attribute: default
