name: Run gitwerk
on:
  push:
    branches:
      - main

jobs:
  semver-auto:
    name: Run semver-auto
    runs-on: ubuntu-latest
    steps:
      - name: Generate github token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      - name: Check out code.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - name: Get latest gitwerk
        run: |
          wget "https://github.com/rinx/gitwerk/releases/latest/download/gitwerk-linux-amd64.zip"
          unzip gitwerk-linux-amd64.zip
      - name: Run gitwerk contextual-semver
        run: |
          ./gitwerk contextual-semver
          git push origin --tags
